title: "Lab"
description: "Bug Bounty | Security Research | CTF Writeups"
remote_theme: pages-themes/just-the-docs
plugins:
- jekyll-remote-theme
- jekyll-seo-tag

# Social Links (These usually appear in the footer or header)
github_username: Sahilmir18
# twitter_username: yourhandle

markdown: kramdown
theme: jekyll-theme-hacker
